[2022-10-18 15:40:01,502] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: read_conf_from_gsheets_and_update_redis.read_from_gsheets_api scheduled__2022-10-18T15:35:00+00:00 [queued]>
[2022-10-18 15:40:01,509] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: read_conf_from_gsheets_and_update_redis.read_from_gsheets_api scheduled__2022-10-18T15:35:00+00:00 [queued]>
[2022-10-18 15:40:01,510] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-18 15:40:01,512] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-10-18 15:40:01,514] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-18 15:40:01,583] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): read_from_gsheets_api> on 2022-10-18 15:35:00+00:00
[2022-10-18 15:40:01,589] {standard_task_runner.py:52} INFO - Started process 301 to run task
[2022-10-18 15:40:01,592] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'read_conf_from_gsheets_and_update_redis', 'read_from_gsheets_api', 'scheduled__2022-10-18T15:35:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/read_conf_from_gsheets_api_and_update_redis.py', '--cfg-path', '/tmp/tmptyvfqswm', '--error-file', '/tmp/tmpg7s17f_a']
[2022-10-18 15:40:01,594] {standard_task_runner.py:80} INFO - Job 6: Subtask read_from_gsheets_api
[2022-10-18 15:40:01,605] {logging_mixin.py:115} WARNING - /root/.cache/pypoetry/virtualenvs/***-tXitOD5F-py3.8/lib/python3.8/site-packages/airflow/configuration.py:525 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2022-10-18 15:40:01,633] {task_command.py:370} INFO - Running <TaskInstance: read_conf_from_gsheets_and_update_redis.read_from_gsheets_api scheduled__2022-10-18T15:35:00+00:00 [running]> on host 6cdf6d517dc4
[2022-10-18 15:40:01,672] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=wais@datakimia.com,david@datakimia.com,juanm@datakimia.com,tomas@datakimia.com
AIRFLOW_CTX_DAG_OWNER=atacana
AIRFLOW_CTX_DAG_ID=read_conf_from_gsheets_and_update_redis
AIRFLOW_CTX_TASK_ID=read_from_gsheets_api
AIRFLOW_CTX_EXECUTION_DATE=2022-10-18T15:35:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-18T15:35:00+00:00
[2022-10-18 15:40:01,720] {__init__.py:49} INFO - file_cache is only supported with oauth2client<4.0.0
[2022-10-18 15:40:01,725] {helpers.py:200} INFO - Going to read from Gsheets API: sheet_id: 1G_dxkjADV4-W0s1GZjXmwPafU-wNRsWnvt5zRDs9FPU range: indication_keywords
[2022-10-18 15:40:02,689] {helpers.py:204} INFO - 4 rows retrieved
[2022-10-18 15:40:02,748] {__init__.py:49} INFO - file_cache is only supported with oauth2client<4.0.0
[2022-10-18 15:40:02,751] {helpers.py:200} INFO - Going to read from Gsheets API: sheet_id: 1u2cLfdRzLXsoypScASGdxNS_UHt0Y04Lq770cCqSMmQ range: keywords
[2022-10-18 15:40:03,516] {helpers.py:204} INFO - 167 rows retrieved
[2022-10-18 15:40:03,570] {__init__.py:49} INFO - file_cache is only supported with oauth2client<4.0.0
[2022-10-18 15:40:03,574] {helpers.py:200} INFO - Going to read from Gsheets API: sheet_id: 1u2cLfdRzLXsoypScASGdxNS_UHt0Y04Lq770cCqSMmQ range: urls_google_alerts
[2022-10-18 15:40:04,391] {helpers.py:204} INFO - 2 rows retrieved
[2022-10-18 15:40:04,454] {__init__.py:49} INFO - file_cache is only supported with oauth2client<4.0.0
[2022-10-18 15:40:04,458] {helpers.py:200} INFO - Going to read from Gsheets API: sheet_id: 1Qyko3Ip7d0MBtJiEREEWBuRlnXGj3kLN_upzIkWhvog range: keywords
[2022-10-18 15:40:05,142] {helpers.py:204} INFO - 66 rows retrieved
[2022-10-18 15:40:05,202] {__init__.py:49} INFO - file_cache is only supported with oauth2client<4.0.0
[2022-10-18 15:40:05,213] {helpers.py:200} INFO - Going to read from Gsheets API: sheet_id: 1Qyko3Ip7d0MBtJiEREEWBuRlnXGj3kLN_upzIkWhvog range: urls_google_alerts
[2022-10-18 15:40:05,897] {helpers.py:204} INFO - 15 rows retrieved
[2022-10-18 15:40:05,919] {helpers.py:257} ERROR - Error trying to read values from google sheet conf file: ['"Lynparza" OR "Olaparib" OR "AZD 2281" OR "AZD-2281" OR "KU-59436" OR "MK-7339" OR "MK 7339" AND "SCLC" OR "Small cell lung cancer"'], error: ['"Lynparza" OR "Olaparib" OR "AZD 2281" OR "AZD-2281" OR "KU-59436" OR "MK-7339" OR "MK 7339" AND "SCLC" OR "Small cell lung cancer"']
[2022-10-18 15:40:05,922] {helpers.py:257} ERROR - Error trying to read values from google sheet conf file: ['"Keytruda" OR "Pembrolizumab" OR "MK 3475" OR "MK3475" OR "MK-3475" OR "SCH 900475" OR "SCH900475" OR "SCH-900475" AND "SCLC" OR "Small cell lung cancer"'], error: ['"Keytruda" OR "Pembrolizumab" OR "MK 3475" OR "MK3475" OR "MK-3475" OR "SCH 900475" OR "SCH900475" OR "SCH-900475" AND "SCLC" OR "Small cell lung cancer"']
[2022-10-18 15:40:05,926] {helpers.py:257} ERROR - Error trying to read values from google sheet conf file: ['"Opdivo" OR "nivolumab" OR "BMS 936558" OR "BMS-936558" OR "MDX 1106" OR "MDX1106" OR "MDX-1106" OR "NSC 748726" OR "NSC748726" OR "NSC-748726" OR "ONO 4538" OR "ONO4538" OR "ONO-4538" AND "SCLC" OR "Small cell lung cancer"'], error: ['"Opdivo" OR "nivolumab" OR "BMS 936558" OR "BMS-936558" OR "MDX 1106" OR "MDX1106" OR "MDX-1106" OR "NSC 748726" OR "NSC748726" OR "NSC-748726" OR "ONO 4538" OR "ONO4538" OR "ONO-4538" AND "SCLC" OR "Small cell lung cancer"']
[2022-10-18 15:40:05,928] {helpers.py:257} ERROR - Error trying to read values from google sheet conf file: ['"Yervoy" OR "ipilimumab" OR "BMS734016" OR "BMS-734016" OR "MDX010" OR "MDX-010" OR "MDX101" OR "MDX-101" AND "SCLC" OR "Small cell lung cancer"'], error: ['"Yervoy" OR "ipilimumab" OR "BMS734016" OR "BMS-734016" OR "MDX010" OR "MDX-010" OR "MDX101" OR "MDX-101" AND "SCLC" OR "Small cell lung cancer"']
[2022-10-18 15:40:05,930] {helpers.py:257} ERROR - Error trying to read values from google sheet conf file: ['"Tecentriq" OR "atezolizumab" OR "MPDL 3280A" OR "MPDL3280A" OR "MPDL-3280A" OR "RG 7446" OR "RG 7746" OR "RG7446" OR "RG-7446" OR "RG7746" OR "RG-7746" OR "RO 5541267" OR "RO5541267" OR "RO-5541267" AND "SCLC" OR "Small cell lung cancer"'], error: ['"Tecentriq" OR "atezolizumab" OR "MPDL 3280A" OR "MPDL3280A" OR "MPDL-3280A" OR "RG 7446" OR "RG 7746" OR "RG7446" OR "RG-7446" OR "RG7746" OR "RG-7746" OR "RO 5541267" OR "RO5541267" OR "RO-5541267" AND "SCLC" OR "Small cell lung cancer"']
[2022-10-18 15:40:05,932] {helpers.py:257} ERROR - Error trying to read values from google sheet conf file: ['"Imfinzi" OR "durvalumab" OR "MEDI 4736" OR "MEDI4736" OR "MEDI-4736" AND "SCLC" OR "Small cell lung cancer"'], error: ['"Imfinzi" OR "durvalumab" OR "MEDI 4736" OR "MEDI4736" OR "MEDI-4736" AND "SCLC" OR "Small cell lung cancer"']
[2022-10-18 15:40:05,934] {helpers.py:257} ERROR - Error trying to read values from google sheet conf file: ['"Keytruda" OR "Pembrolizumab" OR "MK 3475" OR "MK3475" OR "MK-3475" OR "SCH 900475" OR "SCH900475" OR "SCH-900475" AND "NSCLC" OR "non small cell lung cancer"'], error: ['"Keytruda" OR "Pembrolizumab" OR "MK 3475" OR "MK3475" OR "MK-3475" OR "SCH 900475" OR "SCH900475" OR "SCH-900475" AND "NSCLC" OR "non small cell lung cancer"']
[2022-10-18 15:40:05,936] {helpers.py:257} ERROR - Error trying to read values from google sheet conf file: ['"Opdivo" OR "nivolumab" OR "BMS 936558" OR "BMS-936558" OR "MDX 1106" OR "MDX1106" OR "MDX-1106" OR "NSC 748726" OR "NSC748726" OR "NSC-748726" OR "ONO 4538" OR "ONO4538" OR "ONO-4538" AND "NSCLC" OR "non small cell lung cancer"'], error: ['"Opdivo" OR "nivolumab" OR "BMS 936558" OR "BMS-936558" OR "MDX 1106" OR "MDX1106" OR "MDX-1106" OR "NSC 748726" OR "NSC748726" OR "NSC-748726" OR "ONO 4538" OR "ONO4538" OR "ONO-4538" AND "NSCLC" OR "non small cell lung cancer"']
[2022-10-18 15:40:05,938] {helpers.py:257} ERROR - Error trying to read values from google sheet conf file: ['"Yervoy" OR "ipilimumab" OR "BMS734016" OR "BMS-734016" OR "MDX010" OR "MDX-010" OR "MDX101" OR "MDX-101" AND "NSCLC" OR "non small cell lung cancer"'], error: ['"Yervoy" OR "ipilimumab" OR "BMS734016" OR "BMS-734016" OR "MDX010" OR "MDX-010" OR "MDX101" OR "MDX-101" AND "NSCLC" OR "non small cell lung cancer"']
[2022-10-18 15:40:05,943] {helpers.py:257} ERROR - Error trying to read values from google sheet conf file: ['"Tecentriq" OR "atezolizumab" OR "MPDL 3280A" OR "MPDL3280A" OR "MPDL-3280A" OR "RG 7446" OR "RG 7746" OR "RG7446" OR "RG-7446" OR "RG7746" OR "RG-7746" OR "RO 5541267" OR "RO5541267" OR "RO-5541267" AND "NSCLC" OR "non small cell lung cancer"'], error: ['"Tecentriq" OR "atezolizumab" OR "MPDL 3280A" OR "MPDL3280A" OR "MPDL-3280A" OR "RG 7446" OR "RG 7746" OR "RG7446" OR "RG-7446" OR "RG7746" OR "RG-7746" OR "RO 5541267" OR "RO5541267" OR "RO-5541267" AND "NSCLC" OR "non small cell lung cancer"']
[2022-10-18 15:40:05,945] {helpers.py:257} ERROR - Error trying to read values from google sheet conf file: ['"Imfinzi" OR "durvalumab" OR "MEDI 4736" OR "MEDI4736" OR "MEDI-4736" AND "NSCLC" OR "non small cell lung cancer"'], error: ['"Imfinzi" OR "durvalumab" OR "MEDI 4736" OR "MEDI4736" OR "MEDI-4736" AND "NSCLC" OR "non small cell lung cancer"']
[2022-10-18 15:40:05,947] {helpers.py:257} ERROR - Error trying to read values from google sheet conf file: ['"Astrazeneca" OR "Merck" OR "BMS" OR "Bristol Myers Squibb" OR "Roche" OR "Genentech" AND "SCLC" OR "Small cell lung cancer"'], error: ['"Astrazeneca" OR "Merck" OR "BMS" OR "Bristol Myers Squibb" OR "Roche" OR "Genentech" AND "SCLC" OR "Small cell lung cancer"']
[2022-10-18 15:40:05,949] {helpers.py:257} ERROR - Error trying to read values from google sheet conf file: ['"Astrazeneca" OR "Merck" OR "BMS" OR "Bristol Myers Squibb" OR "Roche" OR "Genentech" AND "NSCLC" OR "non small cell lung cancer"'], error: ['"Astrazeneca" OR "Merck" OR "BMS" OR "Bristol Myers Squibb" OR "Roche" OR "Genentech" AND "NSCLC" OR "non small cell lung cancer"']
[2022-10-18 15:40:06,000] {__init__.py:49} INFO - file_cache is only supported with oauth2client<4.0.0
[2022-10-18 15:40:06,004] {helpers.py:200} INFO - Going to read from Gsheets API: sheet_id: 1-c-h8NeaYz-yAo6FsxRZGpeRb-A5a56mq6rrFqeyI6M/ range: keywords
[2022-10-18 15:40:06,594] {helpers.py:208} ERROR - An error occurred: <HttpError 404 when requesting https://sheets.googleapis.com/v4/spreadsheets/1-c-h8NeaYz-yAo6FsxRZGpeRb-A5a56mq6rrFqeyI6M%2F/values/keywords?alt=json returned "Requested entity was not found.". Details: "Requested entity was not found.">
[2022-10-18 15:40:06,599] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/pharma-news-tXitOD5F-py3.8/lib/python3.8/site-packages/airflow/decorators/base.py", line 179, in execute
    return_value = super().execute(context)
  File "/root/.cache/pypoetry/virtualenvs/pharma-news-tXitOD5F-py3.8/lib/python3.8/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/root/.cache/pypoetry/virtualenvs/pharma-news-tXitOD5F-py3.8/lib/python3.8/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/etc/airflow/dags/read_conf_from_gsheets_api_and_update_redis.py", line 28, in read_from_gsheets_api
    return get_indication_keywords_conf()
  File "/news-project/pharma_news/helpers.py", line 239, in get_indication_keywords_conf
    keywords = get_values_from_sheet_api(keywords_sheet_id, "keywords")
  File "/news-project/pharma_news/helpers.py", line 209, in get_values_from_sheet_api
    raise error
  File "/news-project/pharma_news/helpers.py", line 201, in get_values_from_sheet_api
    result = service.spreadsheets().values().get(
  File "/root/.cache/pypoetry/virtualenvs/pharma-news-tXitOD5F-py3.8/lib/python3.8/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/pharma-news-tXitOD5F-py3.8/lib/python3.8/site-packages/googleapiclient/http.py", line 938, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 404 when requesting https://sheets.googleapis.com/v4/spreadsheets/1-c-h8NeaYz-yAo6FsxRZGpeRb-A5a56mq6rrFqeyI6M%2F/values/keywords?alt=json returned "Requested entity was not found.". Details: "Requested entity was not found.">
[2022-10-18 15:40:06,625] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=read_conf_from_gsheets_and_update_redis, task_id=read_from_gsheets_api, execution_date=20221018T153500, start_date=20221018T154001, end_date=20221018T154006
[2022-10-18 15:40:06,641] {logging_mixin.py:115} WARNING - /root/.cache/pypoetry/virtualenvs/***-tXitOD5F-py3.8/lib/python3.8/site-packages/airflow/utils/email.py:119 PendingDeprecationWarning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2022-10-18 15:40:06,642] {email.py:228} INFO - Email alerting: attempt 1
[2022-10-18 15:40:06,957] {email.py:228} INFO - Email alerting: attempt 1
[2022-10-18 15:40:06,965] {taskinstance.py:1944} ERROR - Failed to send email to: ['wais@datakimia.com', 'david@datakimia.com', 'juanm@datakimia.com', 'tomas@datakimia.com']
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/pharma-news-tXitOD5F-py3.8/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1451, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/root/.cache/pypoetry/virtualenvs/pharma-news-tXitOD5F-py3.8/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1598, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/root/.cache/pypoetry/virtualenvs/pharma-news-tXitOD5F-py3.8/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1659, in _execute_task
    result = execute_callable(context=context)
  File "/root/.cache/pypoetry/virtualenvs/pharma-news-tXitOD5F-py3.8/lib/python3.8/site-packages/airflow/decorators/base.py", line 179, in execute
    return_value = super().execute(context)
  File "/root/.cache/pypoetry/virtualenvs/pharma-news-tXitOD5F-py3.8/lib/python3.8/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/root/.cache/pypoetry/virtualenvs/pharma-news-tXitOD5F-py3.8/lib/python3.8/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/etc/airflow/dags/read_conf_from_gsheets_api_and_update_redis.py", line 28, in read_from_gsheets_api
    return get_indication_keywords_conf()
  File "/news-project/pharma_news/helpers.py", line 239, in get_indication_keywords_conf
    keywords = get_values_from_sheet_api(keywords_sheet_id, "keywords")
  File "/news-project/pharma_news/helpers.py", line 209, in get_values_from_sheet_api
    raise error
  File "/news-project/pharma_news/helpers.py", line 201, in get_values_from_sheet_api
    result = service.spreadsheets().values().get(
  File "/root/.cache/pypoetry/virtualenvs/pharma-news-tXitOD5F-py3.8/lib/python3.8/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/pharma-news-tXitOD5F-py3.8/lib/python3.8/site-packages/googleapiclient/http.py", line 938, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 404 when requesting https://sheets.googleapis.com/v4/spreadsheets/1-c-h8NeaYz-yAo6FsxRZGpeRb-A5a56mq6rrFqeyI6M%2F/values/keywords?alt=json returned "Requested entity was not found.". Details: "Requested entity was not found.">

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/pharma-news-tXitOD5F-py3.8/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2326, in email_alert
    send_email(task.email, subject, html_content)
  File "/root/.cache/pypoetry/virtualenvs/pharma-news-tXitOD5F-py3.8/lib/python3.8/site-packages/airflow/utils/email.py", line 58, in send_email
    return backend(
  File "/root/.cache/pypoetry/virtualenvs/pharma-news-tXitOD5F-py3.8/lib/python3.8/site-packages/airflow/utils/email.py", line 119, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/root/.cache/pypoetry/virtualenvs/pharma-news-tXitOD5F-py3.8/lib/python3.8/site-packages/airflow/utils/email.py", line 230, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/root/.cache/pypoetry/virtualenvs/pharma-news-tXitOD5F-py3.8/lib/python3.8/site-packages/airflow/utils/email.py", line 264, in _get_smtp_connection
    else smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.8/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 310, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/local/lib/python3.8/socket.py", line 787, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/local/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/pharma-news-tXitOD5F-py3.8/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1942, in handle_failure
    self.email_alert(error, task)
  File "/root/.cache/pypoetry/virtualenvs/pharma-news-tXitOD5F-py3.8/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2328, in email_alert
    send_email(task.email, subject, html_content_err)
  File "/root/.cache/pypoetry/virtualenvs/pharma-news-tXitOD5F-py3.8/lib/python3.8/site-packages/airflow/utils/email.py", line 58, in send_email
    return backend(
  File "/root/.cache/pypoetry/virtualenvs/pharma-news-tXitOD5F-py3.8/lib/python3.8/site-packages/airflow/utils/email.py", line 119, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/root/.cache/pypoetry/virtualenvs/pharma-news-tXitOD5F-py3.8/lib/python3.8/site-packages/airflow/utils/email.py", line 230, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/root/.cache/pypoetry/virtualenvs/pharma-news-tXitOD5F-py3.8/lib/python3.8/site-packages/airflow/utils/email.py", line 264, in _get_smtp_connection
    else smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.8/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 310, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/local/lib/python3.8/socket.py", line 787, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/local/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
[2022-10-18 15:40:06,981] {standard_task_runner.py:92} ERROR - Failed to execute job 6 for task read_from_gsheets_api (<HttpError 404 when requesting https://sheets.googleapis.com/v4/spreadsheets/1-c-h8NeaYz-yAo6FsxRZGpeRb-A5a56mq6rrFqeyI6M%2F/values/keywords?alt=json returned "Requested entity was not found.". Details: "Requested entity was not found.">; 301)
[2022-10-18 15:40:07,037] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-10-18 15:40:07,059] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
